from pathlib import Path
p = Path('/var/www/bazaar/dashboard/public/bloc/index.html')
text = p.read_text()

old = "function deriveLabRows(rows,params){const out=rows.map(r=>({...r}));for(let i=0;i<out.length;i++){const start=Math.max(0,i-11),win=out.slice(start,i+1),prices=win.map(r=>r.price),vols=win.map(r=>r.volume||0),mid=prices.reduce((a,b)=>a+b,0)/prices.length,prev=out[i-1]?.price??out[i].price,prev2=out[i-2]?.price??prev,ret1=prev?((out[i].price-prev)/prev)*100:0,prevRet=prev2?((prev-prev2)/prev2)*100:0;out[i].midpoint=mid;out[i].distance=Math.abs(mid?((out[i].price-mid)/mid)*100:0);out[i].pullback=mid?((mid-Math.min(...prices))/mid)*100:0;out[i].reversal=(prevRet<0&&ret1>0)?Math.abs(prevRet)+Math.abs(ret1):0;out[i].volRatio=vols.reduce((a,b)=>a+b,0)?((out[i].volume||0)/(vols.reduce((a,b)=>a+b,0)/vols.length)):1;out[i].volatility=mid?((Math.max(...prices)-Math.min(...prices))/mid)*100:0;out[i].accel=ret1-prevRet;}return out;}"
new = old + "function simulateLabTrades(rows,params){const trades=[];let i=12;while(i<rows.length-1){const r=rows[i];const entryOk=r.price<=r.midpoint&&r.distance>=params.distance_min&&r.pullback>=params.pullback_min&&r.reversal>=params.reversal_min&&r.volRatio>=params.volume_ratio_min&&r.volatility>=params.volatility_min&&r.accel>=params.accel_min;if(!entryOk){i++;continue;}const entry=r.price;let peak=entry,exit=entry,reason='hold',exitIdx=i;for(let j=i+1;j<Math.min(rows.length,i+1+Math.max(1,params.max_hold_bars));j++){const p=rows[j].price;peak=Math.max(peak,p);const profit=((p-entry)/entry)*100;const retrace=peak>0?((peak-p)/peak)*100:0;if(profit<=-(params.stop_pct||0)){exit=p;exitIdx=j;reason='stop';break;}if(profit>=(params.target_pct||0)&&retrace>=(params.retrace_pct||0)){exit=p;exitIdx=j;reason='target';break;}if(profit>=(params.trail_trigger_pct||0)&&retrace>=(params.retrace_pct||0)){exit=p;exitIdx=j;reason='trail';break;}exit=p;exitIdx=j;reason='hold_end';}trades.push({entryIdx:i,exitIdx,entryPrice:entry,exitPrice:exit,netPct:(((exit-entry)/entry)*100)-(params.friction_pct||0),reason});i=exitIdx+1;}return trades;}"
text = text.replace(old, new)

old2 = "const rows=deriveLabRows(labMarket.rows||[],params);const hits=rows.filter(r=>r.price<=r.midpoint&&r.distance>=params.distance_min&&r.pullback>=params.pullback_min&&r.reversal>=params.reversal_min&&r.volRatio>=params.volume_ratio_min&&r.volatility>=params.volatility_min&&r.accel>=params.accel_min);$('labMsg').textContent=`${hits.length} candidate reversals under current visible thresholds`;const c=$('labChart'),x=c.getContext('2d'),W=c.width,H=c.height,padL=72,padR=20,padT=18,padB=40;x.clearRect(0,0,W,H);"
new2 = "const rows=deriveLabRows(labMarket.rows||[],params);const hits=rows.filter(r=>r.price<=r.midpoint&&r.distance>=params.distance_min&&r.pullback>=params.pullback_min&&r.reversal>=params.reversal_min&&r.volRatio>=params.volume_ratio_min&&r.volatility>=params.volatility_min&&r.accel>=params.accel_min);const trades=simulateLabTrades(rows,params);const winners=trades.filter(t=>t.netPct>0).length;$('labMsg').textContent=`${hits.length} candidate entries · ${trades.length} simulated trades · ${winners} winners`;const c=$('labChart'),x=c.getContext('2d'),W=c.width,H=c.height,padL=72,padR=20,padT=18,padB=40;x.clearRect(0,0,W,H);"
text = text.replace(old2, new2)

old3 = "hits.forEach(r=>{const i=rows.indexOf(r);x.fillStyle='#20d29a';x.beginPath();x.arc(px(i),py(r.price),3.5,0,Math.PI*2);x.fill();});$('labSamples').textContent=String(rows.length);"
new3 = "trades.forEach(t=>{const gain=t.netPct>=0; x.strokeStyle=gain?'rgba(32,210,154,.55)':'rgba(255,93,115,.55)'; x.lineWidth=2; x.beginPath(); x.moveTo(px(t.entryIdx),py(t.entryPrice)); x.lineTo(px(t.exitIdx),py(t.exitPrice)); x.stroke(); x.fillStyle='#20d29a'; x.beginPath(); x.arc(px(t.entryIdx),py(t.entryPrice),3.5,0,Math.PI*2); x.fill(); x.fillStyle=gain?'#7ec8ff':'#ff5d73'; x.beginPath(); x.arc(px(t.exitIdx),py(t.exitPrice),3.5,0,Math.PI*2); x.fill();});hits.forEach(r=>{const i=rows.indexOf(r);x.fillStyle='rgba(32,210,154,.25)';x.beginPath();x.arc(px(i),py(r.price),2.5,0,Math.PI*2);x.fill();});$('labSamples').textContent=String(rows.length);"
text = text.replace(old3, new3)

p.write_text(text)
print('ok')
