#!/usr/bin/env python3
from __future__ import annotations

import json
import os
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
REPLAY = ROOT / 'eth_scalper' / 'scripts' / 'replay_live_bloc_protocol.py'
SUMMARY = ROOT / 'eth_scalper' / 'out' / 'live_bloc_replay_summary.json'
OUT = ROOT / 'out' / 'eth_btc_rotator_tuning.json'

PARAM_SETS = [
    {'name':'r1','MIN_WETH_ACCUMULATION_PCT':0.02,'REENTRY_SCORE_THRESHOLD':0.20,'REENTRY_SCORE_ARM_THRESHOLD':0.12,'REENTRY_REANALYZE_VOL_MULTIPLIER':0.35,'VOL_MULTIPLIER':0.90,'STOP_LOSS':1.00,'COOLDOWN_BARS':2},
    {'name':'r2','MIN_WETH_ACCUMULATION_PCT':0.03,'REENTRY_SCORE_THRESHOLD':0.24,'REENTRY_SCORE_ARM_THRESHOLD':0.14,'REENTRY_REANALYZE_VOL_MULTIPLIER':0.40,'VOL_MULTIPLIER':0.95,'STOP_LOSS':0.90,'COOLDOWN_BARS':2},
    {'name':'r3','MIN_WETH_ACCUMULATION_PCT':0.04,'REENTRY_SCORE_THRESHOLD':0.28,'REENTRY_SCORE_ARM_THRESHOLD':0.16,'REENTRY_REANALYZE_VOL_MULTIPLIER':0.45,'VOL_MULTIPLIER':1.00,'STOP_LOSS':0.85,'COOLDOWN_BARS':2},
    {'name':'r4','MIN_WETH_ACCUMULATION_PCT':0.05,'REENTRY_SCORE_THRESHOLD':0.22,'REENTRY_SCORE_ARM_THRESHOLD':0.10,'REENTRY_REANALYZE_VOL_MULTIPLIER':0.30,'VOL_MULTIPLIER':0.85,'STOP_LOSS':1.10,'COOLDOWN_BARS':1},
    {'name':'r5','MIN_WETH_ACCUMULATION_PCT':0.06,'REENTRY_SCORE_THRESHOLD':0.26,'REENTRY_SCORE_ARM_THRESHOLD':0.15,'REENTRY_REANALYZE_VOL_MULTIPLIER':0.50,'VOL_MULTIPLIER':1.05,'STOP_LOSS':0.95,'COOLDOWN_BARS':2},
    {'name':'r6','MIN_WETH_ACCUMULATION_PCT':0.08,'REENTRY_SCORE_THRESHOLD':0.30,'REENTRY_SCORE_ARM_THRESHOLD':0.18,'REENTRY_REANALYZE_VOL_MULTIPLIER':0.55,'VOL_MULTIPLIER':1.10,'STOP_LOSS':0.80,'COOLDOWN_BARS':3},
    {'name':'r7','MIN_WETH_ACCUMULATION_PCT':0.10,'REENTRY_SCORE_THRESHOLD':0.18,'REENTRY_SCORE_ARM_THRESHOLD':0.09,'REENTRY_REANALYZE_VOL_MULTIPLIER':0.25,'VOL_MULTIPLIER':0.80,'STOP_LOSS':1.20,'COOLDOWN_BARS':1},
    {'name':'r8','MIN_WETH_ACCUMULATION_PCT':0.12,'REENTRY_SCORE_THRESHOLD':0.34,'REENTRY_SCORE_ARM_THRESHOLD':0.20,'REENTRY_REANALYZE_VOL_MULTIPLIER':0.60,'VOL_MULTIPLIER':1.15,'STOP_LOSS':0.75,'COOLDOWN_BARS':3},
    {'name':'r9','MIN_WETH_ACCUMULATION_PCT':0.02,'REENTRY_SCORE_THRESHOLD':0.16,'REENTRY_SCORE_ARM_THRESHOLD':0.08,'REENTRY_REANALYZE_VOL_MULTIPLIER':0.20,'VOL_MULTIPLIER':0.75,'STOP_LOSS':1.25,'COOLDOWN_BARS':1},
    {'name':'r10','MIN_WETH_ACCUMULATION_PCT':0.03,'REENTRY_SCORE_THRESHOLD':0.32,'REENTRY_SCORE_ARM_THRESHOLD':0.18,'REENTRY_REANALYZE_VOL_MULTIPLIER':0.65,'VOL_MULTIPLIER':1.20,'STOP_LOSS':0.70,'COOLDOWN_BARS':4},
    {'name':'r11','MIN_WETH_ACCUMULATION_PCT':0.04,'REENTRY_SCORE_THRESHOLD':0.14,'REENTRY_SCORE_ARM_THRESHOLD':0.07,'REENTRY_REANALYZE_VOL_MULTIPLIER':0.20,'VOL_MULTIPLIER':0.70,'STOP_LOSS':1.30,'COOLDOWN_BARS':1},
    {'name':'r12','MIN_WETH_ACCUMULATION_PCT':0.05,'REENTRY_SCORE_THRESHOLD':0.36,'REENTRY_SCORE_ARM_THRESHOLD':0.22,'REENTRY_REANALYZE_VOL_MULTIPLIER':0.70,'VOL_MULTIPLIER':1.25,'STOP_LOSS':0.65,'COOLDOWN_BARS':4},
    {'name':'r13','MIN_WETH_ACCUMULATION_PCT':0.06,'REENTRY_SCORE_THRESHOLD':0.12,'REENTRY_SCORE_ARM_THRESHOLD':0.06,'REENTRY_REANALYZE_VOL_MULTIPLIER':0.18,'VOL_MULTIPLIER':0.68,'STOP_LOSS':1.35,'COOLDOWN_BARS':1},
    {'name':'r14','MIN_WETH_ACCUMULATION_PCT':0.07,'REENTRY_SCORE_THRESHOLD':0.21,'REENTRY_SCORE_ARM_THRESHOLD':0.11,'REENTRY_REANALYZE_VOL_MULTIPLIER':0.28,'VOL_MULTIPLIER':0.82,'STOP_LOSS':1.05,'COOLDOWN_BARS':2},
    {'name':'r15','MIN_WETH_ACCUMULATION_PCT':0.08,'REENTRY_SCORE_THRESHOLD':0.27,'REENTRY_SCORE_ARM_THRESHOLD':0.15,'REENTRY_REANALYZE_VOL_MULTIPLIER':0.38,'VOL_MULTIPLIER':0.92,'STOP_LOSS':0.98,'COOLDOWN_BARS':2},
    {'name':'r16','MIN_WETH_ACCUMULATION_PCT':0.09,'REENTRY_SCORE_THRESHOLD':0.31,'REENTRY_SCORE_ARM_THRESHOLD':0.17,'REENTRY_REANALYZE_VOL_MULTIPLIER':0.48,'VOL_MULTIPLIER':1.02,'STOP_LOSS':0.88,'COOLDOWN_BARS':3},
    {'name':'r17','MIN_WETH_ACCUMULATION_PCT':0.10,'REENTRY_SCORE_THRESHOLD':0.19,'REENTRY_SCORE_ARM_THRESHOLD':0.10,'REENTRY_REANALYZE_VOL_MULTIPLIER':0.26,'VOL_MULTIPLIER':0.78,'STOP_LOSS':1.15,'COOLDOWN_BARS':1},
    {'name':'r18','MIN_WETH_ACCUMULATION_PCT':0.11,'REENTRY_SCORE_THRESHOLD':0.23,'REENTRY_SCORE_ARM_THRESHOLD':0.12,'REENTRY_REANALYZE_VOL_MULTIPLIER':0.32,'VOL_MULTIPLIER':0.88,'STOP_LOSS':1.08,'COOLDOWN_BARS':2},
    {'name':'r19','MIN_WETH_ACCUMULATION_PCT':0.12,'REENTRY_SCORE_THRESHOLD':0.29,'REENTRY_SCORE_ARM_THRESHOLD':0.16,'REENTRY_REANALYZE_VOL_MULTIPLIER':0.42,'VOL_MULTIPLIER':0.98,'STOP_LOSS':0.92,'COOLDOWN_BARS':3},
    {'name':'r20','MIN_WETH_ACCUMULATION_PCT':0.14,'REENTRY_SCORE_THRESHOLD':0.35,'REENTRY_SCORE_ARM_THRESHOLD':0.20,'REENTRY_REANALYZE_VOL_MULTIPLIER':0.58,'VOL_MULTIPLIER':1.12,'STOP_LOSS':0.78,'COOLDOWN_BARS':4},
]


def run_one(params: dict) -> dict:
    env = os.environ.copy()
    env.update({k: str(v) for k, v in params.items() if k != 'name'})
    subprocess.run(['python3', str(REPLAY)], cwd=str(ROOT), env=env, check=True, capture_output=True, text=True)
    summary = json.loads(SUMMARY.read_text())
    return {'name': params['name'], 'params': params, 'summary': summary}


def rank_key(item: dict):
    s = item['summary']
    return (
        float(s.get('eth_equiv_delta_units') or -999999),
        float(s.get('eth_equiv_return_pct') or -999999),
        float(s.get('rotate_count') or 0),
        float(s.get('trade_count') or 0),
    )


def main() -> None:
    results = [run_one(p) for p in PARAM_SETS]
    ranked = sorted(results, key=rank_key, reverse=True)
    out = {
        'tested': len(results),
        'objective': 'eth_equiv_delta_units',
        'top3': ranked[:3],
        'ranking': [r['name'] for r in ranked],
        'results': results,
    }
    OUT.write_text(json.dumps(out, indent=2))
    print(json.dumps({'tested': out['tested'], 'top3': out['top3'], 'ranking': out['ranking'][:10]}, indent=2))


if __name__ == '__main__':
    main()
