#!/usr/bin/env python3
from __future__ import annotations

import json
import os
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
REPLAY = ROOT / 'eth_scalper' / 'scripts' / 'replay_live_bloc_protocol.py'
SUMMARY = ROOT / 'eth_scalper' / 'out' / 'live_bloc_replay_summary.json'
OUT = ROOT / 'out' / 'eth_btc_rotator_tuning_v2.json'

PARAM_SETS = [
    {'name':'s1','MIN_WETH_ACCUMULATION_PCT':-0.02,'REENTRY_SCORE_THRESHOLD':0.08,'REENTRY_SCORE_ARM_THRESHOLD':0.04,'PAIR_SPREAD_TRIGGER_PCT':0.10,'PAIR_REVERSAL_TRIGGER_PCT':0.04,'PAIR_ROTATE_MIN_EDGE_PCT':-0.01,'PAIR_ROTATE_EXIT_EDGE_PCT':0.00,'VOL_MULTIPLIER':0.70,'STOP_LOSS':1.40,'COOLDOWN_BARS':1},
    {'name':'s2','MIN_WETH_ACCUMULATION_PCT':-0.01,'REENTRY_SCORE_THRESHOLD':0.10,'REENTRY_SCORE_ARM_THRESHOLD':0.05,'PAIR_SPREAD_TRIGGER_PCT':0.12,'PAIR_REVERSAL_TRIGGER_PCT':0.05,'PAIR_ROTATE_MIN_EDGE_PCT':0.00,'PAIR_ROTATE_EXIT_EDGE_PCT':0.00,'VOL_MULTIPLIER':0.75,'STOP_LOSS':1.30,'COOLDOWN_BARS':1},
    {'name':'s3','MIN_WETH_ACCUMULATION_PCT':0.00,'REENTRY_SCORE_THRESHOLD':0.12,'REENTRY_SCORE_ARM_THRESHOLD':0.06,'PAIR_SPREAD_TRIGGER_PCT':0.14,'PAIR_REVERSAL_TRIGGER_PCT':0.06,'PAIR_ROTATE_MIN_EDGE_PCT':0.01,'PAIR_ROTATE_EXIT_EDGE_PCT':0.005,'VOL_MULTIPLIER':0.80,'STOP_LOSS':1.20,'COOLDOWN_BARS':1},
    {'name':'s4','MIN_WETH_ACCUMULATION_PCT':0.01,'REENTRY_SCORE_THRESHOLD':0.14,'REENTRY_SCORE_ARM_THRESHOLD':0.07,'PAIR_SPREAD_TRIGGER_PCT':0.16,'PAIR_REVERSAL_TRIGGER_PCT':0.07,'PAIR_ROTATE_MIN_EDGE_PCT':0.015,'PAIR_ROTATE_EXIT_EDGE_PCT':0.005,'VOL_MULTIPLIER':0.85,'STOP_LOSS':1.10,'COOLDOWN_BARS':1},
    {'name':'s5','MIN_WETH_ACCUMULATION_PCT':0.02,'REENTRY_SCORE_THRESHOLD':0.16,'REENTRY_SCORE_ARM_THRESHOLD':0.08,'PAIR_SPREAD_TRIGGER_PCT':0.18,'PAIR_REVERSAL_TRIGGER_PCT':0.08,'PAIR_ROTATE_MIN_EDGE_PCT':0.02,'PAIR_ROTATE_EXIT_EDGE_PCT':0.01,'VOL_MULTIPLIER':0.90,'STOP_LOSS':1.00,'COOLDOWN_BARS':2},
    {'name':'s6','MIN_WETH_ACCUMULATION_PCT':0.03,'REENTRY_SCORE_THRESHOLD':0.18,'REENTRY_SCORE_ARM_THRESHOLD':0.09,'PAIR_SPREAD_TRIGGER_PCT':0.20,'PAIR_REVERSAL_TRIGGER_PCT':0.09,'PAIR_ROTATE_MIN_EDGE_PCT':0.03,'PAIR_ROTATE_EXIT_EDGE_PCT':0.01,'VOL_MULTIPLIER':0.95,'STOP_LOSS':0.95,'COOLDOWN_BARS':2},
    {'name':'s7','MIN_WETH_ACCUMULATION_PCT':-0.03,'REENTRY_SCORE_THRESHOLD':0.06,'REENTRY_SCORE_ARM_THRESHOLD':0.03,'PAIR_SPREAD_TRIGGER_PCT':0.08,'PAIR_REVERSAL_TRIGGER_PCT':0.03,'PAIR_ROTATE_MIN_EDGE_PCT':-0.02,'PAIR_ROTATE_EXIT_EDGE_PCT':0.00,'VOL_MULTIPLIER':0.65,'STOP_LOSS':1.50,'COOLDOWN_BARS':1},
    {'name':'s8','MIN_WETH_ACCUMULATION_PCT':0.00,'REENTRY_SCORE_THRESHOLD':0.09,'REENTRY_SCORE_ARM_THRESHOLD':0.05,'PAIR_SPREAD_TRIGGER_PCT':0.11,'PAIR_REVERSAL_TRIGGER_PCT':0.04,'PAIR_ROTATE_MIN_EDGE_PCT':0.00,'PAIR_ROTATE_EXIT_EDGE_PCT':0.00,'VOL_MULTIPLIER':0.72,'STOP_LOSS':1.35,'COOLDOWN_BARS':1},
    {'name':'s9','MIN_WETH_ACCUMULATION_PCT':0.01,'REENTRY_SCORE_THRESHOLD':0.11,'REENTRY_SCORE_ARM_THRESHOLD':0.06,'PAIR_SPREAD_TRIGGER_PCT':0.13,'PAIR_REVERSAL_TRIGGER_PCT':0.05,'PAIR_ROTATE_MIN_EDGE_PCT':0.005,'PAIR_ROTATE_EXIT_EDGE_PCT':0.002,'VOL_MULTIPLIER':0.78,'STOP_LOSS':1.25,'COOLDOWN_BARS':1},
    {'name':'s10','MIN_WETH_ACCUMULATION_PCT':0.02,'REENTRY_SCORE_THRESHOLD':0.13,'REENTRY_SCORE_ARM_THRESHOLD':0.07,'PAIR_SPREAD_TRIGGER_PCT':0.15,'PAIR_REVERSAL_TRIGGER_PCT':0.06,'PAIR_ROTATE_MIN_EDGE_PCT':0.01,'PAIR_ROTATE_EXIT_EDGE_PCT':0.003,'VOL_MULTIPLIER':0.82,'STOP_LOSS':1.15,'COOLDOWN_BARS':1},
    {'name':'s11','MIN_WETH_ACCUMULATION_PCT':0.03,'REENTRY_SCORE_THRESHOLD':0.15,'REENTRY_SCORE_ARM_THRESHOLD':0.08,'PAIR_SPREAD_TRIGGER_PCT':0.17,'PAIR_REVERSAL_TRIGGER_PCT':0.07,'PAIR_ROTATE_MIN_EDGE_PCT':0.015,'PAIR_ROTATE_EXIT_EDGE_PCT':0.004,'VOL_MULTIPLIER':0.88,'STOP_LOSS':1.05,'COOLDOWN_BARS':2},
    {'name':'s12','MIN_WETH_ACCUMULATION_PCT':0.04,'REENTRY_SCORE_THRESHOLD':0.17,'REENTRY_SCORE_ARM_THRESHOLD':0.09,'PAIR_SPREAD_TRIGGER_PCT':0.19,'PAIR_REVERSAL_TRIGGER_PCT':0.08,'PAIR_ROTATE_MIN_EDGE_PCT':0.02,'PAIR_ROTATE_EXIT_EDGE_PCT':0.005,'VOL_MULTIPLIER':0.92,'STOP_LOSS':0.98,'COOLDOWN_BARS':2},
]


def run_one(params: dict) -> dict:
    env = os.environ.copy()
    env.update({k: str(v) for k, v in params.items() if k != 'name'})
    subprocess.run(['python3', str(REPLAY)], cwd=str(ROOT), env=env, check=True, capture_output=True, text=True)
    summary = json.loads(SUMMARY.read_text())
    return {'name': params['name'], 'params': params, 'summary': summary}


def rank_key(item: dict):
    s = item['summary']
    return (
        float(s.get('eth_equiv_delta_units') or -999999),
        float(s.get('eth_equiv_return_pct') or -999999),
        float(s.get('rotate_count') or 0),
        -float(s.get('stop_count') or 999999),
    )


def main() -> None:
    results = [run_one(p) for p in PARAM_SETS]
    ranked = sorted(results, key=rank_key, reverse=True)
    out = {'tested': len(results), 'objective': 'eth_equiv_delta_units', 'top3': ranked[:3], 'results': results}
    OUT.write_text(json.dumps(out, indent=2))
    print(json.dumps({'tested': out['tested'], 'top3': out['top3']}, indent=2))


if __name__ == '__main__':
    main()
